version: '3'

services:
  db:
    image: postgres:13.7
    privileged: true
    restart: always
    ports:
      - 54325:5432
    environment:
      POSTGRES_DB: catalog
      POSTGRES_USER: django
      POSTGRES_PASSWORD: qwerty
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data

