# Generated by Django 4.0.1 on 2022-05-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HitCount',
            fields=[
                ('path', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=1)),
            ],
        ),
    ]
