# Generated by Django 4.0.1 on 2022-05-29 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hitcount', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hitcount',
            old_name='count',
            new_name='hits',
        ),
    ]
